// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5pprVRBOckmhpAUuySbaO2HTyEEFZC1c',
    appId: '1:1068388499914:web:cc3e5f2daff6ef22e88f33',
    messagingSenderId: '1068388499914',
    projectId: 'farah-zone',
    authDomain: 'farah-zone.firebaseapp.com',
    storageBucket: 'farah-zone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRoElTyySVIl1kCNOM-7NZiVKSV6V_s_M',
    appId: '1:1068388499914:android:984e41dd98bb705ee88f33',
    messagingSenderId: '1068388499914',
    projectId: 'farah-zone',
    storageBucket: 'farah-zone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAsAGAGmddu-B1IPSMA-opmKzNSHQ60d0',
    appId: '1:1068388499914:ios:85d147cb72b237a3e88f33',
    messagingSenderId: '1068388499914',
    projectId: 'farah-zone',
    storageBucket: 'farah-zone.firebasestorage.app',
    iosBundleId: 'com.example.farah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAsAGAGmddu-B1IPSMA-opmKzNSHQ60d0',
    appId: '1:1068388499914:ios:85d147cb72b237a3e88f33',
    messagingSenderId: '1068388499914',
    projectId: 'farah-zone',
    storageBucket: 'farah-zone.firebasestorage.app',
    iosBundleId: 'com.example.farah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5pprVRBOckmhpAUuySbaO2HTyEEFZC1c',
    appId: '1:1068388499914:web:ce054c30cd39903ae88f33',
    messagingSenderId: '1068388499914',
    projectId: 'farah-zone',
    authDomain: 'farah-zone.firebaseapp.com',
    storageBucket: 'farah-zone.firebasestorage.app',
  );
}
